### ISSUE TITLE
Include LICENSE file

### ISSUE THREAD

**Issue by igor-raits** [rabite0/osstrtools#2]
I'm packaging hunter with all its dependencies for Fedora. However, what is missing in all crates is the LICENSE file with full text of WTFPL.

I would appreciate if you would include it.

Aside, putting Cargo.lock into the library-crates does not do anything useful.

**Comment by rabite0** [comment]
Wow, that's great!
I included a LICENSE in all my own libraries and pushed updates to github/crates.io. I also removed Cargo.lock, at your suggestion.
